# Conda environment config
# You might need to install PyTorch manually based on your desired device (CPU/GPU) and CUDA version (for NVIDIA GPUs)
# Reference: https://pytorch.org/get-started/locally/
name: dynamic-zoom
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - numpy
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - pip:
      - opencv-python
